### ISSUE TITLE
leaderelection errror

### ISSUE THREAD

**Issue by jvizier** [duyanghao/velero-volume-controller#1]
Hi,

I try to install velero-volume-controller

Here the logs :

    E0417 04:32:24.215510       1 leaderelection.go:324] error initially creating leader election record: 
    the server could not find the requested resource
    I0417 04:32:24.215527       1 leaderelection.go:247] failed to acquire lease backup/velero-volume- 
    controller

K8S 1.13

I try also to change in cluster-role.yaml leases to endpoints but same error.

Regards

**Comment by duyanghao** [comment]
@jvizier It seems that `velero-volume-controller` is deployed in `backup` namespace but the default serviceAccount namespace of ClusterRoleBinding is `velero` as [this yaml](https://github.com/duyanghao/velero-volume-controller/blob/master/examples/deployment/cluster-role-binding.yaml) shows, so you may need to change it as below:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-volume-controller
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: backup
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: leaselock
  apiGroup: rbac.authorization.k8s.io
```

Closing this out, but feel free to reach out again as needed.
